#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

# General bar and defaults

sketchybar --bar height=30 \
	color=0x00000000 \
	shadow="$SHADOW" \
  font_smoothing=on \
  notch_width=0 \
	position=top \
	sticky=off \
	padding_right=10 \
	padding_left=0 \
	corner_radius=10 \
	y_offset=5 \
	margin=670 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:12" \
	icon.color="$ICON_COLOR" \
	icon.padding_left="$PADDINGS" \
	icon.padding_right="$PADDINGS" \
	label.font="$FONT:Bold:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left="$PADDINGS" \
	label.padding_right="$PADDINGS" \
	background.padding_right="$PADDINGS" \
	background.padding_left="$PADDINGS" \
	popup.background.border_width=1 \
	popup.background.corner_radius=11 \
	popup.background.border_color="$POPUP_BORDER_COLOR" \
	popup.background.color="$POPUP_BACKGROUND_COLOR" \
	popup.background.shadow.drawing="$SHADOW"

# Left
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/cpu_temp.sh"

# Center (of notch)

# Right
source "$ITEM_DIR/battery.sh"
#################### Finalizing Setup ####################

sketchybar --hotload true

sketchybar --update

echo "sketchybar configuration loaded.."
