wsl = false
no-multigrid = true
maximized = false
srgb = false
idle = true
frame = "transparent"
title-hidden = true
tabs = false

[font]
normal = ["FiraCode Nerd Font Mono"]
style = "SemiBold"
size = 17
